Redress release pipeline (#26)

diff --git a/dev/build b/dev/build
--- a/dev/build
+++ b/dev/build
@@ -8,10 +8,18 @@ if ! git diff-index --quiet HEAD --; then
   echo "Uncommitted changes!" && exit 0;
 fi
 
+# Test fake build before build
+if ! dzil test; then
+  echo "Build test failed!" && exit 0;
+fi
+
+# Cleanup build
+dzil clean
+
 # Build Package
 dzil build
 
-# Push generated POD changes
+# Commit generated POD changes
 if ! git diff-index --quiet HEAD --; then
   git checkout CHANGES && git add . && git commit -m 'Update documentation'
 fi
